name: 'Upload Everest CI artifact'
inputs:
  name:
    description: 'Name of the artifact, e.g. FStar'
    required: true
  path:
    description: 'Directory to compress and upload'
    required: true
  extra:
    description: 'Extra arguments for tar'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Tar
      shell: bash
      run: tar czf '${{ inputs.name }}.tar.gz' ${{ inputs.extra }} '${{ inputs.path }}'

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        path: ${{ inputs.name }}.tar.gz
        name: ${{ inputs.name }}
        retention-days: 1
