name: 'Upload Everest CI artifact'
inputs:
  name:
    description: 'Name of the artifact, e.g. FStar'
    required: true
  path:
    description: 'Directory to compress and upload (defaults to the name if unset)'
  hometag:
    description: 'If present, downloaders will get a <tag>_HOME env variable set'
    default: ''
  extra:
    description: 'Extra arguments for tar'
    default: ''
  exclude_git:
    description: 'Exclude .git in the path. Defaults to true'
    default: true

runs:
  using: "composite"
  steps:
    - name: compute exclude_git
      shell: bash
      run: |
        if [ -z '${{inputs.exclude_git}}' ]; then
          echo "EXCLUDE_GIT=" >>$GITHUB_ENV
        else
          echo "EXCLUDE_GIT=--exclude=${{inputs.path || inputs.name}}/.git" >>$GITHUB_ENV
        fi

    - name: Create hometag files
      if: ${{ inputs.hometag }}
      run: |
        echo ${{ inputs.hometag }} > ${{ inputs.path }}/.hometag

    - name: Create tarball
      shell: bash
      run: |
        tar czf '${{ inputs.name }}.tar.gz' \
          ${{ inputs.extra }} \
          "${EXCLUDE_GIT}" \
          '${{ inputs.path || inputs.name }}'

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        path: ${{ inputs.name }}.tar.gz
        name: ${{ inputs.name }}
        retention-days: 1
